services:
  api: &main_app
    build:
      context: .
      dockerfile: ./Dockerfile
    image: rayka_api:${RAYKA_API_VERSION:-latest}
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      # redis:
      #   condition: service_healthy
      # rmq:
      #   condition: service_healthy
    environment:
      RAYKA_API_HOST: 0.0.0.0
      RAYKA_API_DB_HOST: rayka_api-db
      RAYKA_API_DB_PORT: 5432
      RAYKA_API_DB_USER: rayka_api
      RAYKA_API_DB_PASS: rayka_api
      RAYKA_API_DB_BASE: rayka_api
      RAYKA_API_RABBIT_HOST: rayka_api-rmq
      RAYKA_API_REDIS_HOST: rayka_api-redis

  db:
    image: postgres:16.3-bullseye
    hostname: rayka_api-db
    environment:
      POSTGRES_PASSWORD: "rayka_api"
      POSTGRES_USER: "rayka_api"
      POSTGRES_DB: "rayka_api"
    volumes:
      - rayka_api-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: pg_isready -U rayka_api
      interval: 2s
      timeout: 3s
      retries: 40

  migrator:
    image: rayka_api:${RAYKA_API_VERSION:-latest}
    restart: "no"
    command: alembic upgrade head
    environment:
      RAYKA_API_DB_HOST: rayka_api-db
      RAYKA_API_DB_PORT: 5432
      RAYKA_API_DB_USER: rayka_api
      RAYKA_API_DB_PASS: rayka_api
      RAYKA_API_DB_BASE: rayka_api
    depends_on:
      db:
        condition: service_healthy

  # redis:
  #   image: bitnami/redis:6.2.5
  #   hostname: "rayka_api-redis"
  #   restart: always
  #   environment:
  #     ALLOW_EMPTY_PASSWORD: "yes"
  #   healthcheck:
  #     test: redis-cli ping
  #     interval: 1s
  #     timeout: 3s
  #     retries: 50

  # rmq:
  #   image: rabbitmq:3.9.16-alpine
  #   hostname: "rayka_api-rmq"
  #   restart: always
  #   environment:
  #     RABBITMQ_DEFAULT_USER: "guest"
  #     RABBITMQ_DEFAULT_PASS: "guest"
  #     RABBITMQ_DEFAULT_VHOST: "/"
  #   healthcheck:
  #     test: rabbitmq-diagnostics check_running -q
  #     interval: 3s
  #     timeout: 3s
  #     retries: 50



volumes:
  rayka_api-db-data:
    name: rayka_api-db-data
